version: "3.8"

services:
  mysql:
    image: mysql/mysql-server:latest
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: flightdb
      MYSQL_USER: springuser      
      MYSQL_PASSWORD: springpassword 
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    container_name: flight-ticket-app
    build: .
    restart: on-failure
    depends_on:
      - mysql
    ports:
      - "8086:8086"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/flightdb
      SPRING_DATASOURCE_USERNAME: springuser  
      SPRING_DATASOURCE_PASSWORD: springpassword

      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL8Dialect
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

volumes:
  mysql_data: